### ISSUE TITLE
Not understanding the `number.g_move_threshold` entities 

### ISSUE THREAD

**Issue by johntdyer** [athua/ha-utils#1]
Its not clear to me what the g*_move_threshold entities come from....

**Comment by athua** [comment]
Please see the ESPHome LD2410 component documentation.
https://esphome.io/components/sensor/ld2410.html

These values are part of the LD2410 component and are setup in your YAML.
They are only available if you are connecting the LD2410 to an ESP board using the TX/RX pins.
If you are using bluetooth to connect the LD2410 to Home Assistant then these charts will not work as the bluetooth integration (https://www.home-assistant.io/integrations/ld2410_ble/) does not expose all the data that is available via the UART TX/RX.
